[package]
name = "con-process"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
] }
